# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_cargo', models.CharField(max_length=30)),
                ('descripcion_cargo', models.TextField()),
                ('ciudad', models.CharField(max_length=20)),
                ('fecha_contratacion', models.DateTimeField()),
                ('sueldo', models.IntegerField()),
                ('tipo_jornada', models.CharField(choices=[('COMPLETA', 'Completa'), ('MEDIA', 'Media'), ('PART_TIME', 'Part time'), ('TURNOS', 'Turnos')], max_length=3)),
                ('tipo_contrato', models.CharField(choices=[('FIJO', 'Plazo fijo'), ('INDEFINIDO', 'Indefinido'), ('HONORARIOS', 'Honorarios')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=50)),
                ('anos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_educacional', models.CharField(choices=[('PRACTICA', 'Pr\xe1ctica'), ('OFICIO', 'Oficio'), ('TECNICA', 'T\xe9cnica'), ('PROFESIONAL', 'Profesional'), ('UNIVERSITARIA', 'Universitaria'), ('INDIFERENTE', 'Indiferente')], max_length=5)),
                ('carrera', models.CharField(max_length=15)),
                ('experiencia', models.IntegerField()),
            ],
        ),
    ]
