# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Requisitos',
            new_name='Requisito',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='anos',
            new_name='anos_experiencia',
        ),
    ]
