# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0002_auto_20180302_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcioncargo',
            name='ciudad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='descripcioncargo',
            name='fecha_contratacion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='descripcioncargo',
            name='tipo_contrato',
            field=models.CharField(choices=[('FIJO', 'Plazo fijo'), ('INDEFINIDO', 'Indefinido'), ('HONORARIOS', 'Honorarios')], max_length=20),
        ),
        migrations.AlterField(
            model_name='descripcioncargo',
            name='tipo_jornada',
            field=models.CharField(choices=[('COMPLETA', 'Completa'), ('MEDIA', 'Media'), ('PART_TIME', 'Part time'), ('TURNOS', 'Turnos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='carrera',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='nivel_educacional',
            field=models.CharField(choices=[('PRACTICA', 'Practicante'), ('OFICIO', 'Nivel oficio'), ('TECNICA', 'Nivel t\xe9cnico'), ('PROFESIONAL', 'Nivel profesional'), ('UNIVERSITARIA', 'Nivel universitaria'), ('INDIFERENTE', 'Indiferente')], max_length=20),
        ),
    ]
