# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 14:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0005_auto_20180302_1141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='name',
            new_name='nombre',
        ),
    ]
