# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0006_auto_20180302_1142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descripcioncargo',
            old_name='titulo',
            new_name='cargo',
        ),
    ]
