# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-02 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0007_auto_20180302_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcioncargo',
            name='estado_publicacion',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='descripcioncargo',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ofertas.Empresa'),
            preserve_default=False,
        ),
    ]
