# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0008_auto_20180302_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcioncargo',
            name='estado_publicacion',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=10),
        ),
    ]
