# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0010_auto_20180306_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcioncargo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
