# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0012_auto_20180306_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcioncargo',
            name='created_at',
        ),
    ]
