# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0013_remove_descripcioncargo_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='anos_experiencia',
            field=models.IntegerField(),
        ),
    ]
