# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ofertas', '0014_auto_20180306_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='anos_experiencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
