# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-07 21:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ofertas', '0016_auto_20180307_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='postular',
            name='postulante_oferta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
